### ISSUE TITLE
Energy measurement recording

### ISSUE THREAD

**Issue by kaankara** [jgoeders/dac_2019_contest#2]
For the energy measurement, after creating the recorder (recorder = pynq.DataRecorder(rails['power1'].power)), we have to start recording (recorder.record(interval_in_seconds)). Otherwise the frame will be empty and energy will be "nan". Maybe this is due to a change in the DataRecorder in the newest version of the pynq image?

**Comment by jgoeders** [comment]
I'm not quite sure I understand what the issue is.  The current sample notebook has the following code that demonstrates the need for performing the recording:
```

    # timer start when PS reading image
    start = time.time()
    
    recorder = pynq.DataRecorder(rails['power1'].power)
    
    with recorder.record(0.01):    
        bgr_array = cv2.imread(get_image_path(first_image))
        rgb_array = cv2.cvtColor(bgr_array, cv2.COLOR_BGR2RGB)
        in_buffer[:] = rgb_array
    
        dma_transfer()

    # timer stop after PS has received image
    end = time.time()
    t = end - start
    
    energy = recorder.frame["power1_power"].mean() * t
    
    print('Processing time: {} seconds.'.format(t))
    print('Energy: {} J.'.format(energy))
```

Is there some other document that we need to update?

**Comment by kaankara** [comment]
Ah my mistake, I missed that line. Thank you!
